// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BulkProduce(arg1) {
  return window['go']['main']['App']['BulkProduce'](arg1);
}

export function ClearOperationLogs() {
  return window['go']['main']['App']['ClearOperationLogs']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CreateTopic(arg1) {
  return window['go']['main']['App']['CreateTopic'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteConsumerGroup(arg1) {
  return window['go']['main']['App']['DeleteConsumerGroup'](arg1);
}

export function DeleteTopic(arg1) {
  return window['go']['main']['App']['DeleteTopic'](arg1);
}

export function DescribeConsumerGroup(arg1) {
  return window['go']['main']['App']['DescribeConsumerGroup'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function FetchMessages(arg1) {
  return window['go']['main']['App']['FetchMessages'](arg1);
}

export function GetActiveConnectionID() {
  return window['go']['main']['App']['GetActiveConnectionID']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetOverview() {
  return window['go']['main']['App']['GetOverview']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function KafkaServiceStatus(arg1) {
  return window['go']['main']['App']['KafkaServiceStatus'](arg1);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListConsumerGroups() {
  return window['go']['main']['App']['ListConsumerGroups']();
}

export function ListOperationLogs() {
  return window['go']['main']['App']['ListOperationLogs']();
}

export function ListTopics() {
  return window['go']['main']['App']['ListTopics']();
}

export function ProduceMessage(arg1) {
  return window['go']['main']['App']['ProduceMessage'](arg1);
}

export function ReadBrokerConfig(arg1) {
  return window['go']['main']['App']['ReadBrokerConfig'](arg1);
}

export function RestartKafkaService(arg1) {
  return window['go']['main']['App']['RestartKafkaService'](arg1);
}

export function SaveBrokerConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveBrokerConfig'](arg1, arg2);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function TestSSH(arg1) {
  return window['go']['main']['App']['TestSSH'](arg1);
}

export function UpdatePartitions(arg1, arg2) {
  return window['go']['main']['App']['UpdatePartitions'](arg1, arg2);
}
