// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function BulkProduce(arg1:model.BulkProduceParams):Promise<model.Result>;

export function ClearOperationLogs():Promise<model.Result>;

export function Connect(arg1:string):Promise<model.Result>;

export function CreateTopic(arg1:model.TopicCreateParams):Promise<model.Result>;

export function DeleteConnection(arg1:string):Promise<model.Result>;

export function DeleteConsumerGroup(arg1:string):Promise<model.Result>;

export function DeleteTopic(arg1:string):Promise<model.Result>;

export function DescribeConsumerGroup(arg1:string):Promise<model.Result>;

export function Disconnect(arg1:string):Promise<model.Result>;

export function FetchMessages(arg1:model.FetchMessagesParams):Promise<model.Result>;

export function GetActiveConnectionID():Promise<string>;

export function GetConfigPath():Promise<string>;

export function GetOverview():Promise<model.Result>;

export function GetVersion():Promise<string>;

export function KafkaServiceStatus(arg1:string):Promise<model.Result>;

export function ListConnections():Promise<model.Result>;

export function ListConsumerGroups():Promise<model.Result>;

export function ListOperationLogs():Promise<model.Result>;

export function ListTopics():Promise<model.Result>;

export function ProduceMessage(arg1:model.ProduceMessageParams):Promise<model.Result>;

export function ReadBrokerConfig(arg1:string):Promise<model.Result>;

export function RestartKafkaService(arg1:string):Promise<model.Result>;

export function SaveBrokerConfig(arg1:string,arg2:string):Promise<model.Result>;

export function SaveConnection(arg1:model.ConnectionProfile):Promise<model.Result>;

export function TestConnection(arg1:model.ConnectionProfile):Promise<model.Result>;

export function TestSSH(arg1:string):Promise<model.Result>;

export function UpdatePartitions(arg1:string,arg2:number):Promise<model.Result>;
